# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc532f278c2f6124fde65681022eb38e06bb8f9f9cacae3726898cbb13b23eb8e5140c1d7ec5af71e2d56362b44fd9723eb64e4d468487af314d316b18d1edc1

test:
  secret_key_base: 252d6b5f54bbfb54b0e9e9bb9e7579074b174b73cc9748032bb6e1c0bcf9af8c6a1f6f0aefe823dae561dc5ccff3a20b70999769b4301c2571b2430bf091aa32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
